### PR TITLE
Multi-database datachecks

### PR DESCRIPTION
**Pull request by james-monkeyshines**
Adding datacheck for testing stable ID uniqueness across many databases/servers.
Tweaking datacheck for species name uniqueness, make it db-level rather than species-level for collection dbs.

### CODE REVIEW

**Comment by thomasmaurel** [comment]
@james-monkeyshines: Did Travis failed because of index.json?

**Comment by james-monkeyshines** [comment]
> @james-monkeyshines: Did Travis failed because of index.json?

Yes. The merge from master has updated that file, but not brought in the corresponding SpeciesTaxonomy datacheck. Also, looks like there's a weird character there, a colon is higlighted in red, but not exactly sure what's going there.

**Comment by james-monkeyshines** [comment]
> > @james-monkeyshines: Did Travis failed because of index.json?
> 
> Yes. The merge from master has updated that file, but not brought in the corresponding SpeciesTaxonomy datacheck. Also, looks like there's a weird character there, a colon is higlighted in red, but not exactly sure what's going there.

Marc spotted the issue, invalidly formatted json. All looks fine now.

**Comment by thomasmaurel** [comment]
All good now.

**Pull request merged**
